# Generated by Django 4.1 on 2022-08-27 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='name',
        ),
        migrations.AddField(
            model_name='applicant',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicant',
            name='linkedin_address',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='sex',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F')], default='M', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('pending', 'P'), ('confirmed', 'c'), ('failed', 'f')], default='P', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
