# Generated by Django 4.1 on 2022-08-28 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0002_remove_applicant_name_applicant_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apt.applicant'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apt.interviewer'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('pending', 'P'), ('confirmed', 'C'), ('failed', 'F')], default='P', max_length=100),
        ),
    ]
