# Generated by Django 4.1 on 2022-08-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0005_interview_createdat_alter_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='telegram_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
